services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # strapi:
  #   image: strapi/strapi
  #   container_name: strapi_backend
  #   restart: always
  #   env_file:
  #     - ./.env
  #   environment:
  #     DATABASE_CLIENT: postgres
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     APP_KEYS: ${STRAPI_APP_KEYS}
  #     JWT_SECRET: ${STRAPI_JWT_SECRET}
  #     NODE_ENV: development
  #   volumes:
  #     - ./strapi:/srv/app
  #     - /srv/app/node_modules
  #   ports:
  #     - "1337:1337"
  #   depends_on:
  #     - postgres
  #   # command: npx create-strapi-app@latest ./ --quickstart

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: react_frontend
  #   restart: always
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:80"
  #   environment:
  #     # URL interna para o frontend consumir a API do Strapi
  #     VITE_STRAPI_API: http://strapi:1337
  #   depends_on:
  #     - strapi
      
volumes:
  postgres_data: